apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: database
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
